/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/_docs'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as WebsiteRouteImport } from './routes/_website'
import { Route as DocsProductionErrorRouteImport } from './routes/_docs.production-error'
import { Route as DocsSolidRouteImport } from './routes/_docs.solid'
import { Route as PrivatePlaygroundRouteImport } from './routes/_private.playground'
import { Route as WebsiteIndexRouteImport } from './routes/_website.index'
import { Route as DocsSolidIndexRouteImport } from './routes/_docs.solid.index'
import { Route as DocsSolidHandbookRouteImport } from './routes/_docs.solid.handbook'
import { Route as DocsSolidOverviewRouteImport } from './routes/_docs.solid.overview'
import { Route as DocsSolidUtilsRouteImport } from './routes/_docs.solid.utils'
import { Route as DocsSolidComponentsIndexRouteImport } from './routes/_docs.solid.components.index'
import { Route as DocsSolidComponentsAccordionRouteImport } from './routes/_docs.solid.components.accordion'
import { Route as DocsSolidComponentsAlertDialogRouteImport } from './routes/_docs.solid.components.alert-dialog'
import { Route as DocsSolidComponentsAutocompleteRouteImport } from './routes/_docs.solid.components.autocomplete'
import { Route as DocsSolidComponentsAvatarRouteImport } from './routes/_docs.solid.components.avatar'
import { Route as DocsSolidComponentsButtonRouteImport } from './routes/_docs.solid.components.button'
import { Route as DocsSolidComponentsCheckboxRouteImport } from './routes/_docs.solid.components.checkbox'
import { Route as DocsSolidComponentsCheckboxGroupRouteImport } from './routes/_docs.solid.components.checkbox-group'
import { Route as DocsSolidComponentsCollapsibleRouteImport } from './routes/_docs.solid.components.collapsible'
import { Route as DocsSolidComponentsComboboxRouteImport } from './routes/_docs.solid.components.combobox'
import { Route as DocsSolidComponentsContextMenuRouteImport } from './routes/_docs.solid.components.context-menu'
import { Route as DocsSolidComponentsDialogRouteImport } from './routes/_docs.solid.components.dialog'
import { Route as DocsSolidComponentsDrawerRouteImport } from './routes/_docs.solid.components.drawer'
import { Route as DocsSolidComponentsFieldRouteImport } from './routes/_docs.solid.components.field'
import { Route as DocsSolidComponentsFieldsetRouteImport } from './routes/_docs.solid.components.fieldset'
import { Route as DocsSolidComponentsFormRouteImport } from './routes/_docs.solid.components.form'
import { Route as DocsSolidComponentsInputRouteImport } from './routes/_docs.solid.components.input'
import { Route as DocsSolidComponentsMenuRouteImport } from './routes/_docs.solid.components.menu'
import { Route as DocsSolidComponentsMenubarRouteImport } from './routes/_docs.solid.components.menubar'
import { Route as DocsSolidComponentsMeterRouteImport } from './routes/_docs.solid.components.meter'
import { Route as DocsSolidComponentsNavigationMenuRouteImport } from './routes/_docs.solid.components.navigation-menu'
import { Route as DocsSolidComponentsNumberFieldRouteImport } from './routes/_docs.solid.components.number-field'
import { Route as DocsSolidComponentsOtpFieldRouteImport } from './routes/_docs.solid.components.otp-field'
import { Route as DocsSolidComponentsPopoverRouteImport } from './routes/_docs.solid.components.popover'
import { Route as DocsSolidComponentsPreviewCardRouteImport } from './routes/_docs.solid.components.preview-card'
import { Route as DocsSolidComponentsProgressRouteImport } from './routes/_docs.solid.components.progress'
import { Route as DocsSolidComponentsRadioGroupRouteImport } from './routes/_docs.solid.components.radio-group'
import { Route as DocsSolidComponentsScrollAreaRouteImport } from './routes/_docs.solid.components.scroll-area'
import { Route as DocsSolidComponentsSelectRouteImport } from './routes/_docs.solid.components.select'
import { Route as DocsSolidComponentsSeparatorRouteImport } from './routes/_docs.solid.components.separator'
import { Route as DocsSolidComponentsSliderRouteImport } from './routes/_docs.solid.components.slider'
import { Route as DocsSolidComponentsSwitchRouteImport } from './routes/_docs.solid.components.switch'
import { Route as DocsSolidComponentsTabsRouteImport } from './routes/_docs.solid.components.tabs'
import { Route as DocsSolidComponentsToastRouteImport } from './routes/_docs.solid.components.toast'
import { Route as DocsSolidComponentsToggleRouteImport } from './routes/_docs.solid.components.toggle'
import { Route as DocsSolidComponentsToggleGroupRouteImport } from './routes/_docs.solid.components.toggle-group'
import { Route as DocsSolidComponentsToolbarRouteImport } from './routes/_docs.solid.components.toolbar'
import { Route as DocsSolidComponentsTooltipRouteImport } from './routes/_docs.solid.components.tooltip'
import { Route as DocsSolidHandbookIndexRouteImport } from './routes/_docs.solid.handbook.index'
import { Route as DocsSolidHandbookAnimationRouteImport } from './routes/_docs.solid.handbook.animation'
import { Route as DocsSolidHandbookCompositionRouteImport } from './routes/_docs.solid.handbook.composition'
import { Route as DocsSolidHandbookCustomizationRouteImport } from './routes/_docs.solid.handbook.customization'
import { Route as DocsSolidHandbookFormsRouteImport } from './routes/_docs.solid.handbook.forms'
import { Route as DocsSolidHandbookStylingRouteImport } from './routes/_docs.solid.handbook.styling'
import { Route as DocsSolidHandbookTypescriptRouteImport } from './routes/_docs.solid.handbook.typescript'
import { Route as DocsSolidOverviewIndexRouteImport } from './routes/_docs.solid.overview.index'
import { Route as DocsSolidOverviewAboutRouteImport } from './routes/_docs.solid.overview.about'
import { Route as DocsSolidOverviewAccessibilityRouteImport } from './routes/_docs.solid.overview.accessibility'
import { Route as DocsSolidOverviewCommunityRouteImport } from './routes/_docs.solid.overview.community'
import { Route as DocsSolidOverviewQuickStartRouteImport } from './routes/_docs.solid.overview.quick-start'
import { Route as DocsSolidOverviewReleasesRouteImport } from './routes/_docs.solid.overview.releases'
import { Route as DocsSolidUtilsIndexRouteImport } from './routes/_docs.solid.utils.index'
import { Route as DocsSolidUtilsCspProviderRouteImport } from './routes/_docs.solid.utils.csp-provider'
import { Route as DocsSolidUtilsDirectionProviderRouteImport } from './routes/_docs.solid.utils.direction-provider'
import { Route as DocsSolidUtilsMergePropsRouteImport } from './routes/_docs.solid.utils.merge-props'
import { Route as DocsSolidUtilsUseRenderRouteImport } from './routes/_docs.solid.utils.use-render'
import { Route as DocsSolidOverviewReleasesIndexRouteImport } from './routes/_docs.solid.overview.releases.index'
import { Route as DocsSolidOverviewReleasesV001RouteImport } from './routes/_docs.solid.overview.releases.v0-0-1'
import { Route as DocsSolidOverviewReleasesV010RouteImport } from './routes/_docs.solid.overview.releases.v0-1-0'

const DocsRoute = DocsRouteImport.update({
  id: '/_docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteRoute = WebsiteRouteImport.update({
  id: '/_website',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsProductionErrorRoute = DocsProductionErrorRouteImport.update({
  id: '/production-error',
  path: '/production-error',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSolidRoute = DocsSolidRouteImport.update({
  id: '/solid',
  path: '/solid',
  getParentRoute: () => DocsRoute,
} as any)
const PrivatePlaygroundRoute = PrivatePlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => PrivateRoute,
} as any)
const WebsiteIndexRoute = WebsiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebsiteRoute,
} as any)
const DocsSolidIndexRoute = DocsSolidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsSolidRoute,
} as any)
const DocsSolidHandbookRoute = DocsSolidHandbookRouteImport.update({
  id: '/handbook',
  path: '/handbook',
  getParentRoute: () => DocsSolidRoute,
} as any)
const DocsSolidOverviewRoute = DocsSolidOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DocsSolidRoute,
} as any)
const DocsSolidUtilsRoute = DocsSolidUtilsRouteImport.update({
  id: '/utils',
  path: '/utils',
  getParentRoute: () => DocsSolidRoute,
} as any)
const DocsSolidComponentsIndexRoute =
  DocsSolidComponentsIndexRouteImport.update({
    id: '/components/',
    path: '/components/',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsAccordionRoute =
  DocsSolidComponentsAccordionRouteImport.update({
    id: '/components/accordion',
    path: '/components/accordion',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsAlertDialogRoute =
  DocsSolidComponentsAlertDialogRouteImport.update({
    id: '/components/alert-dialog',
    path: '/components/alert-dialog',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsAutocompleteRoute =
  DocsSolidComponentsAutocompleteRouteImport.update({
    id: '/components/autocomplete',
    path: '/components/autocomplete',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsAvatarRoute =
  DocsSolidComponentsAvatarRouteImport.update({
    id: '/components/avatar',
    path: '/components/avatar',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsButtonRoute =
  DocsSolidComponentsButtonRouteImport.update({
    id: '/components/button',
    path: '/components/button',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsCheckboxRoute =
  DocsSolidComponentsCheckboxRouteImport.update({
    id: '/components/checkbox',
    path: '/components/checkbox',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsCheckboxGroupRoute =
  DocsSolidComponentsCheckboxGroupRouteImport.update({
    id: '/components/checkbox-group',
    path: '/components/checkbox-group',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsCollapsibleRoute =
  DocsSolidComponentsCollapsibleRouteImport.update({
    id: '/components/collapsible',
    path: '/components/collapsible',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsComboboxRoute =
  DocsSolidComponentsComboboxRouteImport.update({
    id: '/components/combobox',
    path: '/components/combobox',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsContextMenuRoute =
  DocsSolidComponentsContextMenuRouteImport.update({
    id: '/components/context-menu',
    path: '/components/context-menu',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsDialogRoute =
  DocsSolidComponentsDialogRouteImport.update({
    id: '/components/dialog',
    path: '/components/dialog',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsDrawerRoute =
  DocsSolidComponentsDrawerRouteImport.update({
    id: '/components/drawer',
    path: '/components/drawer',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsFieldRoute =
  DocsSolidComponentsFieldRouteImport.update({
    id: '/components/field',
    path: '/components/field',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsFieldsetRoute =
  DocsSolidComponentsFieldsetRouteImport.update({
    id: '/components/fieldset',
    path: '/components/fieldset',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsFormRoute = DocsSolidComponentsFormRouteImport.update({
  id: '/components/form',
  path: '/components/form',
  getParentRoute: () => DocsSolidRoute,
} as any)
const DocsSolidComponentsInputRoute =
  DocsSolidComponentsInputRouteImport.update({
    id: '/components/input',
    path: '/components/input',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsMenuRoute = DocsSolidComponentsMenuRouteImport.update({
  id: '/components/menu',
  path: '/components/menu',
  getParentRoute: () => DocsSolidRoute,
} as any)
const DocsSolidComponentsMenubarRoute =
  DocsSolidComponentsMenubarRouteImport.update({
    id: '/components/menubar',
    path: '/components/menubar',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsMeterRoute =
  DocsSolidComponentsMeterRouteImport.update({
    id: '/components/meter',
    path: '/components/meter',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsNavigationMenuRoute =
  DocsSolidComponentsNavigationMenuRouteImport.update({
    id: '/components/navigation-menu',
    path: '/components/navigation-menu',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsNumberFieldRoute =
  DocsSolidComponentsNumberFieldRouteImport.update({
    id: '/components/number-field',
    path: '/components/number-field',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsOtpFieldRoute =
  DocsSolidComponentsOtpFieldRouteImport.update({
    id: '/components/otp-field',
    path: '/components/otp-field',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsPopoverRoute =
  DocsSolidComponentsPopoverRouteImport.update({
    id: '/components/popover',
    path: '/components/popover',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsPreviewCardRoute =
  DocsSolidComponentsPreviewCardRouteImport.update({
    id: '/components/preview-card',
    path: '/components/preview-card',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsProgressRoute =
  DocsSolidComponentsProgressRouteImport.update({
    id: '/components/progress',
    path: '/components/progress',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsRadioGroupRoute =
  DocsSolidComponentsRadioGroupRouteImport.update({
    id: '/components/radio-group',
    path: '/components/radio-group',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsScrollAreaRoute =
  DocsSolidComponentsScrollAreaRouteImport.update({
    id: '/components/scroll-area',
    path: '/components/scroll-area',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsSelectRoute =
  DocsSolidComponentsSelectRouteImport.update({
    id: '/components/select',
    path: '/components/select',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsSeparatorRoute =
  DocsSolidComponentsSeparatorRouteImport.update({
    id: '/components/separator',
    path: '/components/separator',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsSliderRoute =
  DocsSolidComponentsSliderRouteImport.update({
    id: '/components/slider',
    path: '/components/slider',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsSwitchRoute =
  DocsSolidComponentsSwitchRouteImport.update({
    id: '/components/switch',
    path: '/components/switch',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsTabsRoute = DocsSolidComponentsTabsRouteImport.update({
  id: '/components/tabs',
  path: '/components/tabs',
  getParentRoute: () => DocsSolidRoute,
} as any)
const DocsSolidComponentsToastRoute =
  DocsSolidComponentsToastRouteImport.update({
    id: '/components/toast',
    path: '/components/toast',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsToggleRoute =
  DocsSolidComponentsToggleRouteImport.update({
    id: '/components/toggle',
    path: '/components/toggle',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsToggleGroupRoute =
  DocsSolidComponentsToggleGroupRouteImport.update({
    id: '/components/toggle-group',
    path: '/components/toggle-group',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsToolbarRoute =
  DocsSolidComponentsToolbarRouteImport.update({
    id: '/components/toolbar',
    path: '/components/toolbar',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidComponentsTooltipRoute =
  DocsSolidComponentsTooltipRouteImport.update({
    id: '/components/tooltip',
    path: '/components/tooltip',
    getParentRoute: () => DocsSolidRoute,
  } as any)
const DocsSolidHandbookIndexRoute = DocsSolidHandbookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsSolidHandbookRoute,
} as any)
const DocsSolidHandbookAnimationRoute =
  DocsSolidHandbookAnimationRouteImport.update({
    id: '/animation',
    path: '/animation',
    getParentRoute: () => DocsSolidHandbookRoute,
  } as any)
const DocsSolidHandbookCompositionRoute =
  DocsSolidHandbookCompositionRouteImport.update({
    id: '/composition',
    path: '/composition',
    getParentRoute: () => DocsSolidHandbookRoute,
  } as any)
const DocsSolidHandbookCustomizationRoute =
  DocsSolidHandbookCustomizationRouteImport.update({
    id: '/customization',
    path: '/customization',
    getParentRoute: () => DocsSolidHandbookRoute,
  } as any)
const DocsSolidHandbookFormsRoute = DocsSolidHandbookFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => DocsSolidHandbookRoute,
} as any)
const DocsSolidHandbookStylingRoute =
  DocsSolidHandbookStylingRouteImport.update({
    id: '/styling',
    path: '/styling',
    getParentRoute: () => DocsSolidHandbookRoute,
  } as any)
const DocsSolidHandbookTypescriptRoute =
  DocsSolidHandbookTypescriptRouteImport.update({
    id: '/typescript',
    path: '/typescript',
    getParentRoute: () => DocsSolidHandbookRoute,
  } as any)
const DocsSolidOverviewIndexRoute = DocsSolidOverviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsSolidOverviewRoute,
} as any)
const DocsSolidOverviewAboutRoute = DocsSolidOverviewAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DocsSolidOverviewRoute,
} as any)
const DocsSolidOverviewAccessibilityRoute =
  DocsSolidOverviewAccessibilityRouteImport.update({
    id: '/accessibility',
    path: '/accessibility',
    getParentRoute: () => DocsSolidOverviewRoute,
  } as any)
const DocsSolidOverviewCommunityRoute =
  DocsSolidOverviewCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => DocsSolidOverviewRoute,
  } as any)
const DocsSolidOverviewQuickStartRoute =
  DocsSolidOverviewQuickStartRouteImport.update({
    id: '/quick-start',
    path: '/quick-start',
    getParentRoute: () => DocsSolidOverviewRoute,
  } as any)
const DocsSolidOverviewReleasesRoute =
  DocsSolidOverviewReleasesRouteImport.update({
    id: '/releases',
    path: '/releases',
    getParentRoute: () => DocsSolidOverviewRoute,
  } as any)
const DocsSolidUtilsIndexRoute = DocsSolidUtilsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsSolidUtilsRoute,
} as any)
const DocsSolidUtilsCspProviderRoute =
  DocsSolidUtilsCspProviderRouteImport.update({
    id: '/csp-provider',
    path: '/csp-provider',
    getParentRoute: () => DocsSolidUtilsRoute,
  } as any)
const DocsSolidUtilsDirectionProviderRoute =
  DocsSolidUtilsDirectionProviderRouteImport.update({
    id: '/direction-provider',
    path: '/direction-provider',
    getParentRoute: () => DocsSolidUtilsRoute,
  } as any)
const DocsSolidUtilsMergePropsRoute =
  DocsSolidUtilsMergePropsRouteImport.update({
    id: '/merge-props',
    path: '/merge-props',
    getParentRoute: () => DocsSolidUtilsRoute,
  } as any)
const DocsSolidUtilsUseRenderRoute = DocsSolidUtilsUseRenderRouteImport.update({
  id: '/use-render',
  path: '/use-render',
  getParentRoute: () => DocsSolidUtilsRoute,
} as any)
const DocsSolidOverviewReleasesIndexRoute =
  DocsSolidOverviewReleasesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DocsSolidOverviewReleasesRoute,
  } as any)
const DocsSolidOverviewReleasesV001Route =
  DocsSolidOverviewReleasesV001RouteImport.update({
    id: '/v0-0-1',
    path: '/v0-0-1',
    getParentRoute: () => DocsSolidOverviewReleasesRoute,
  } as any)
const DocsSolidOverviewReleasesV010Route =
  DocsSolidOverviewReleasesV010RouteImport.update({
    id: '/v0-1-0',
    path: '/v0-1-0',
    getParentRoute: () => DocsSolidOverviewReleasesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WebsiteIndexRoute
  '/production-error': typeof DocsProductionErrorRoute
  '/solid': typeof DocsSolidRouteWithChildren
  '/playground': typeof PrivatePlaygroundRoute
  '/solid/handbook': typeof DocsSolidHandbookRouteWithChildren
  '/solid/overview': typeof DocsSolidOverviewRouteWithChildren
  '/solid/utils': typeof DocsSolidUtilsRouteWithChildren
  '/solid/': typeof DocsSolidIndexRoute
  '/solid/components/accordion': typeof DocsSolidComponentsAccordionRoute
  '/solid/components/alert-dialog': typeof DocsSolidComponentsAlertDialogRoute
  '/solid/components/autocomplete': typeof DocsSolidComponentsAutocompleteRoute
  '/solid/components/avatar': typeof DocsSolidComponentsAvatarRoute
  '/solid/components/button': typeof DocsSolidComponentsButtonRoute
  '/solid/components/checkbox': typeof DocsSolidComponentsCheckboxRoute
  '/solid/components/checkbox-group': typeof DocsSolidComponentsCheckboxGroupRoute
  '/solid/components/collapsible': typeof DocsSolidComponentsCollapsibleRoute
  '/solid/components/combobox': typeof DocsSolidComponentsComboboxRoute
  '/solid/components/context-menu': typeof DocsSolidComponentsContextMenuRoute
  '/solid/components/dialog': typeof DocsSolidComponentsDialogRoute
  '/solid/components/drawer': typeof DocsSolidComponentsDrawerRoute
  '/solid/components/field': typeof DocsSolidComponentsFieldRoute
  '/solid/components/fieldset': typeof DocsSolidComponentsFieldsetRoute
  '/solid/components/form': typeof DocsSolidComponentsFormRoute
  '/solid/components/input': typeof DocsSolidComponentsInputRoute
  '/solid/components/menu': typeof DocsSolidComponentsMenuRoute
  '/solid/components/menubar': typeof DocsSolidComponentsMenubarRoute
  '/solid/components/meter': typeof DocsSolidComponentsMeterRoute
  '/solid/components/navigation-menu': typeof DocsSolidComponentsNavigationMenuRoute
  '/solid/components/number-field': typeof DocsSolidComponentsNumberFieldRoute
  '/solid/components/otp-field': typeof DocsSolidComponentsOtpFieldRoute
  '/solid/components/popover': typeof DocsSolidComponentsPopoverRoute
  '/solid/components/preview-card': typeof DocsSolidComponentsPreviewCardRoute
  '/solid/components/progress': typeof DocsSolidComponentsProgressRoute
  '/solid/components/radio-group': typeof DocsSolidComponentsRadioGroupRoute
  '/solid/components/scroll-area': typeof DocsSolidComponentsScrollAreaRoute
  '/solid/components/select': typeof DocsSolidComponentsSelectRoute
  '/solid/components/separator': typeof DocsSolidComponentsSeparatorRoute
  '/solid/components/slider': typeof DocsSolidComponentsSliderRoute
  '/solid/components/switch': typeof DocsSolidComponentsSwitchRoute
  '/solid/components/tabs': typeof DocsSolidComponentsTabsRoute
  '/solid/components/toast': typeof DocsSolidComponentsToastRoute
  '/solid/components/toggle': typeof DocsSolidComponentsToggleRoute
  '/solid/components/toggle-group': typeof DocsSolidComponentsToggleGroupRoute
  '/solid/components/toolbar': typeof DocsSolidComponentsToolbarRoute
  '/solid/components/tooltip': typeof DocsSolidComponentsTooltipRoute
  '/solid/handbook/animation': typeof DocsSolidHandbookAnimationRoute
  '/solid/handbook/composition': typeof DocsSolidHandbookCompositionRoute
  '/solid/handbook/customization': typeof DocsSolidHandbookCustomizationRoute
  '/solid/handbook/forms': typeof DocsSolidHandbookFormsRoute
  '/solid/handbook/styling': typeof DocsSolidHandbookStylingRoute
  '/solid/handbook/typescript': typeof DocsSolidHandbookTypescriptRoute
  '/solid/overview/about': typeof DocsSolidOverviewAboutRoute
  '/solid/overview/accessibility': typeof DocsSolidOverviewAccessibilityRoute
  '/solid/overview/community': typeof DocsSolidOverviewCommunityRoute
  '/solid/overview/quick-start': typeof DocsSolidOverviewQuickStartRoute
  '/solid/overview/releases': typeof DocsSolidOverviewReleasesRouteWithChildren
  '/solid/utils/csp-provider': typeof DocsSolidUtilsCspProviderRoute
  '/solid/utils/direction-provider': typeof DocsSolidUtilsDirectionProviderRoute
  '/solid/utils/merge-props': typeof DocsSolidUtilsMergePropsRoute
  '/solid/utils/use-render': typeof DocsSolidUtilsUseRenderRoute
  '/solid/components/': typeof DocsSolidComponentsIndexRoute
  '/solid/handbook/': typeof DocsSolidHandbookIndexRoute
  '/solid/overview/': typeof DocsSolidOverviewIndexRoute
  '/solid/utils/': typeof DocsSolidUtilsIndexRoute
  '/solid/overview/releases/v0-0-1': typeof DocsSolidOverviewReleasesV001Route
  '/solid/overview/releases/v0-1-0': typeof DocsSolidOverviewReleasesV010Route
  '/solid/overview/releases/': typeof DocsSolidOverviewReleasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof WebsiteIndexRoute
  '/production-error': typeof DocsProductionErrorRoute
  '/playground': typeof PrivatePlaygroundRoute
  '/solid': typeof DocsSolidIndexRoute
  '/solid/components/accordion': typeof DocsSolidComponentsAccordionRoute
  '/solid/components/alert-dialog': typeof DocsSolidComponentsAlertDialogRoute
  '/solid/components/autocomplete': typeof DocsSolidComponentsAutocompleteRoute
  '/solid/components/avatar': typeof DocsSolidComponentsAvatarRoute
  '/solid/components/button': typeof DocsSolidComponentsButtonRoute
  '/solid/components/checkbox': typeof DocsSolidComponentsCheckboxRoute
  '/solid/components/checkbox-group': typeof DocsSolidComponentsCheckboxGroupRoute
  '/solid/components/collapsible': typeof DocsSolidComponentsCollapsibleRoute
  '/solid/components/combobox': typeof DocsSolidComponentsComboboxRoute
  '/solid/components/context-menu': typeof DocsSolidComponentsContextMenuRoute
  '/solid/components/dialog': typeof DocsSolidComponentsDialogRoute
  '/solid/components/drawer': typeof DocsSolidComponentsDrawerRoute
  '/solid/components/field': typeof DocsSolidComponentsFieldRoute
  '/solid/components/fieldset': typeof DocsSolidComponentsFieldsetRoute
  '/solid/components/form': typeof DocsSolidComponentsFormRoute
  '/solid/components/input': typeof DocsSolidComponentsInputRoute
  '/solid/components/menu': typeof DocsSolidComponentsMenuRoute
  '/solid/components/menubar': typeof DocsSolidComponentsMenubarRoute
  '/solid/components/meter': typeof DocsSolidComponentsMeterRoute
  '/solid/components/navigation-menu': typeof DocsSolidComponentsNavigationMenuRoute
  '/solid/components/number-field': typeof DocsSolidComponentsNumberFieldRoute
  '/solid/components/otp-field': typeof DocsSolidComponentsOtpFieldRoute
  '/solid/components/popover': typeof DocsSolidComponentsPopoverRoute
  '/solid/components/preview-card': typeof DocsSolidComponentsPreviewCardRoute
  '/solid/components/progress': typeof DocsSolidComponentsProgressRoute
  '/solid/components/radio-group': typeof DocsSolidComponentsRadioGroupRoute
  '/solid/components/scroll-area': typeof DocsSolidComponentsScrollAreaRoute
  '/solid/components/select': typeof DocsSolidComponentsSelectRoute
  '/solid/components/separator': typeof DocsSolidComponentsSeparatorRoute
  '/solid/components/slider': typeof DocsSolidComponentsSliderRoute
  '/solid/components/switch': typeof DocsSolidComponentsSwitchRoute
  '/solid/components/tabs': typeof DocsSolidComponentsTabsRoute
  '/solid/components/toast': typeof DocsSolidComponentsToastRoute
  '/solid/components/toggle': typeof DocsSolidComponentsToggleRoute
  '/solid/components/toggle-group': typeof DocsSolidComponentsToggleGroupRoute
  '/solid/components/toolbar': typeof DocsSolidComponentsToolbarRoute
  '/solid/components/tooltip': typeof DocsSolidComponentsTooltipRoute
  '/solid/handbook/animation': typeof DocsSolidHandbookAnimationRoute
  '/solid/handbook/composition': typeof DocsSolidHandbookCompositionRoute
  '/solid/handbook/customization': typeof DocsSolidHandbookCustomizationRoute
  '/solid/handbook/forms': typeof DocsSolidHandbookFormsRoute
  '/solid/handbook/styling': typeof DocsSolidHandbookStylingRoute
  '/solid/handbook/typescript': typeof DocsSolidHandbookTypescriptRoute
  '/solid/overview/about': typeof DocsSolidOverviewAboutRoute
  '/solid/overview/accessibility': typeof DocsSolidOverviewAccessibilityRoute
  '/solid/overview/community': typeof DocsSolidOverviewCommunityRoute
  '/solid/overview/quick-start': typeof DocsSolidOverviewQuickStartRoute
  '/solid/utils/csp-provider': typeof DocsSolidUtilsCspProviderRoute
  '/solid/utils/direction-provider': typeof DocsSolidUtilsDirectionProviderRoute
  '/solid/utils/merge-props': typeof DocsSolidUtilsMergePropsRoute
  '/solid/utils/use-render': typeof DocsSolidUtilsUseRenderRoute
  '/solid/components': typeof DocsSolidComponentsIndexRoute
  '/solid/handbook': typeof DocsSolidHandbookIndexRoute
  '/solid/overview': typeof DocsSolidOverviewIndexRoute
  '/solid/utils': typeof DocsSolidUtilsIndexRoute
  '/solid/overview/releases/v0-0-1': typeof DocsSolidOverviewReleasesV001Route
  '/solid/overview/releases/v0-1-0': typeof DocsSolidOverviewReleasesV010Route
  '/solid/overview/releases': typeof DocsSolidOverviewReleasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_docs': typeof DocsRouteWithChildren
  '/_private': typeof PrivateRouteWithChildren
  '/_website': typeof WebsiteRouteWithChildren
  '/_docs/production-error': typeof DocsProductionErrorRoute
  '/_docs/solid': typeof DocsSolidRouteWithChildren
  '/_private/playground': typeof PrivatePlaygroundRoute
  '/_website/': typeof WebsiteIndexRoute
  '/_docs/solid/handbook': typeof DocsSolidHandbookRouteWithChildren
  '/_docs/solid/overview': typeof DocsSolidOverviewRouteWithChildren
  '/_docs/solid/utils': typeof DocsSolidUtilsRouteWithChildren
  '/_docs/solid/': typeof DocsSolidIndexRoute
  '/_docs/solid/components/accordion': typeof DocsSolidComponentsAccordionRoute
  '/_docs/solid/components/alert-dialog': typeof DocsSolidComponentsAlertDialogRoute
  '/_docs/solid/components/autocomplete': typeof DocsSolidComponentsAutocompleteRoute
  '/_docs/solid/components/avatar': typeof DocsSolidComponentsAvatarRoute
  '/_docs/solid/components/button': typeof DocsSolidComponentsButtonRoute
  '/_docs/solid/components/checkbox': typeof DocsSolidComponentsCheckboxRoute
  '/_docs/solid/components/checkbox-group': typeof DocsSolidComponentsCheckboxGroupRoute
  '/_docs/solid/components/collapsible': typeof DocsSolidComponentsCollapsibleRoute
  '/_docs/solid/components/combobox': typeof DocsSolidComponentsComboboxRoute
  '/_docs/solid/components/context-menu': typeof DocsSolidComponentsContextMenuRoute
  '/_docs/solid/components/dialog': typeof DocsSolidComponentsDialogRoute
  '/_docs/solid/components/drawer': typeof DocsSolidComponentsDrawerRoute
  '/_docs/solid/components/field': typeof DocsSolidComponentsFieldRoute
  '/_docs/solid/components/fieldset': typeof DocsSolidComponentsFieldsetRoute
  '/_docs/solid/components/form': typeof DocsSolidComponentsFormRoute
  '/_docs/solid/components/input': typeof DocsSolidComponentsInputRoute
  '/_docs/solid/components/menu': typeof DocsSolidComponentsMenuRoute
  '/_docs/solid/components/menubar': typeof DocsSolidComponentsMenubarRoute
  '/_docs/solid/components/meter': typeof DocsSolidComponentsMeterRoute
  '/_docs/solid/components/navigation-menu': typeof DocsSolidComponentsNavigationMenuRoute
  '/_docs/solid/components/number-field': typeof DocsSolidComponentsNumberFieldRoute
  '/_docs/solid/components/otp-field': typeof DocsSolidComponentsOtpFieldRoute
  '/_docs/solid/components/popover': typeof DocsSolidComponentsPopoverRoute
  '/_docs/solid/components/preview-card': typeof DocsSolidComponentsPreviewCardRoute
  '/_docs/solid/components/progress': typeof DocsSolidComponentsProgressRoute
  '/_docs/solid/components/radio-group': typeof DocsSolidComponentsRadioGroupRoute
  '/_docs/solid/components/scroll-area': typeof DocsSolidComponentsScrollAreaRoute
  '/_docs/solid/components/select': typeof DocsSolidComponentsSelectRoute
  '/_docs/solid/components/separator': typeof DocsSolidComponentsSeparatorRoute
  '/_docs/solid/components/slider': typeof DocsSolidComponentsSliderRoute
  '/_docs/solid/components/switch': typeof DocsSolidComponentsSwitchRoute
  '/_docs/solid/components/tabs': typeof DocsSolidComponentsTabsRoute
  '/_docs/solid/components/toast': typeof DocsSolidComponentsToastRoute
  '/_docs/solid/components/toggle': typeof DocsSolidComponentsToggleRoute
  '/_docs/solid/components/toggle-group': typeof DocsSolidComponentsToggleGroupRoute
  '/_docs/solid/components/toolbar': typeof DocsSolidComponentsToolbarRoute
  '/_docs/solid/components/tooltip': typeof DocsSolidComponentsTooltipRoute
  '/_docs/solid/handbook/animation': typeof DocsSolidHandbookAnimationRoute
  '/_docs/solid/handbook/composition': typeof DocsSolidHandbookCompositionRoute
  '/_docs/solid/handbook/customization': typeof DocsSolidHandbookCustomizationRoute
  '/_docs/solid/handbook/forms': typeof DocsSolidHandbookFormsRoute
  '/_docs/solid/handbook/styling': typeof DocsSolidHandbookStylingRoute
  '/_docs/solid/handbook/typescript': typeof DocsSolidHandbookTypescriptRoute
  '/_docs/solid/overview/about': typeof DocsSolidOverviewAboutRoute
  '/_docs/solid/overview/accessibility': typeof DocsSolidOverviewAccessibilityRoute
  '/_docs/solid/overview/community': typeof DocsSolidOverviewCommunityRoute
  '/_docs/solid/overview/quick-start': typeof DocsSolidOverviewQuickStartRoute
  '/_docs/solid/overview/releases': typeof DocsSolidOverviewReleasesRouteWithChildren
  '/_docs/solid/utils/csp-provider': typeof DocsSolidUtilsCspProviderRoute
  '/_docs/solid/utils/direction-provider': typeof DocsSolidUtilsDirectionProviderRoute
  '/_docs/solid/utils/merge-props': typeof DocsSolidUtilsMergePropsRoute
  '/_docs/solid/utils/use-render': typeof DocsSolidUtilsUseRenderRoute
  '/_docs/solid/components/': typeof DocsSolidComponentsIndexRoute
  '/_docs/solid/handbook/': typeof DocsSolidHandbookIndexRoute
  '/_docs/solid/overview/': typeof DocsSolidOverviewIndexRoute
  '/_docs/solid/utils/': typeof DocsSolidUtilsIndexRoute
  '/_docs/solid/overview/releases/v0-0-1': typeof DocsSolidOverviewReleasesV001Route
  '/_docs/solid/overview/releases/v0-1-0': typeof DocsSolidOverviewReleasesV010Route
  '/_docs/solid/overview/releases/': typeof DocsSolidOverviewReleasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/production-error'
    | '/solid'
    | '/playground'
    | '/solid/handbook'
    | '/solid/overview'
    | '/solid/utils'
    | '/solid/'
    | '/solid/components/accordion'
    | '/solid/components/alert-dialog'
    | '/solid/components/autocomplete'
    | '/solid/components/avatar'
    | '/solid/components/button'
    | '/solid/components/checkbox'
    | '/solid/components/checkbox-group'
    | '/solid/components/collapsible'
    | '/solid/components/combobox'
    | '/solid/components/context-menu'
    | '/solid/components/dialog'
    | '/solid/components/drawer'
    | '/solid/components/field'
    | '/solid/components/fieldset'
    | '/solid/components/form'
    | '/solid/components/input'
    | '/solid/components/menu'
    | '/solid/components/menubar'
    | '/solid/components/meter'
    | '/solid/components/navigation-menu'
    | '/solid/components/number-field'
    | '/solid/components/otp-field'
    | '/solid/components/popover'
    | '/solid/components/preview-card'
    | '/solid/components/progress'
    | '/solid/components/radio-group'
    | '/solid/components/scroll-area'
    | '/solid/components/select'
    | '/solid/components/separator'
    | '/solid/components/slider'
    | '/solid/components/switch'
    | '/solid/components/tabs'
    | '/solid/components/toast'
    | '/solid/components/toggle'
    | '/solid/components/toggle-group'
    | '/solid/components/toolbar'
    | '/solid/components/tooltip'
    | '/solid/handbook/animation'
    | '/solid/handbook/composition'
    | '/solid/handbook/customization'
    | '/solid/handbook/forms'
    | '/solid/handbook/styling'
    | '/solid/handbook/typescript'
    | '/solid/overview/about'
    | '/solid/overview/accessibility'
    | '/solid/overview/community'
    | '/solid/overview/quick-start'
    | '/solid/overview/releases'
    | '/solid/utils/csp-provider'
    | '/solid/utils/direction-provider'
    | '/solid/utils/merge-props'
    | '/solid/utils/use-render'
    | '/solid/components/'
    | '/solid/handbook/'
    | '/solid/overview/'
    | '/solid/utils/'
    | '/solid/overview/releases/v0-0-1'
    | '/solid/overview/releases/v0-1-0'
    | '/solid/overview/releases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/production-error'
    | '/playground'
    | '/solid'
    | '/solid/components/accordion'
    | '/solid/components/alert-dialog'
    | '/solid/components/autocomplete'
    | '/solid/components/avatar'
    | '/solid/components/button'
    | '/solid/components/checkbox'
    | '/solid/components/checkbox-group'
    | '/solid/components/collapsible'
    | '/solid/components/combobox'
    | '/solid/components/context-menu'
    | '/solid/components/dialog'
    | '/solid/components/drawer'
    | '/solid/components/field'
    | '/solid/components/fieldset'
    | '/solid/components/form'
    | '/solid/components/input'
    | '/solid/components/menu'
    | '/solid/components/menubar'
    | '/solid/components/meter'
    | '/solid/components/navigation-menu'
    | '/solid/components/number-field'
    | '/solid/components/otp-field'
    | '/solid/components/popover'
    | '/solid/components/preview-card'
    | '/solid/components/progress'
    | '/solid/components/radio-group'
    | '/solid/components/scroll-area'
    | '/solid/components/select'
    | '/solid/components/separator'
    | '/solid/components/slider'
    | '/solid/components/switch'
    | '/solid/components/tabs'
    | '/solid/components/toast'
    | '/solid/components/toggle'
    | '/solid/components/toggle-group'
    | '/solid/components/toolbar'
    | '/solid/components/tooltip'
    | '/solid/handbook/animation'
    | '/solid/handbook/composition'
    | '/solid/handbook/customization'
    | '/solid/handbook/forms'
    | '/solid/handbook/styling'
    | '/solid/handbook/typescript'
    | '/solid/overview/about'
    | '/solid/overview/accessibility'
    | '/solid/overview/community'
    | '/solid/overview/quick-start'
    | '/solid/utils/csp-provider'
    | '/solid/utils/direction-provider'
    | '/solid/utils/merge-props'
    | '/solid/utils/use-render'
    | '/solid/components'
    | '/solid/handbook'
    | '/solid/overview'
    | '/solid/utils'
    | '/solid/overview/releases/v0-0-1'
    | '/solid/overview/releases/v0-1-0'
    | '/solid/overview/releases'
  id:
    | '__root__'
    | '/_docs'
    | '/_private'
    | '/_website'
    | '/_docs/production-error'
    | '/_docs/solid'
    | '/_private/playground'
    | '/_website/'
    | '/_docs/solid/handbook'
    | '/_docs/solid/overview'
    | '/_docs/solid/utils'
    | '/_docs/solid/'
    | '/_docs/solid/components/accordion'
    | '/_docs/solid/components/alert-dialog'
    | '/_docs/solid/components/autocomplete'
    | '/_docs/solid/components/avatar'
    | '/_docs/solid/components/button'
    | '/_docs/solid/components/checkbox'
    | '/_docs/solid/components/checkbox-group'
    | '/_docs/solid/components/collapsible'
    | '/_docs/solid/components/combobox'
    | '/_docs/solid/components/context-menu'
    | '/_docs/solid/components/dialog'
    | '/_docs/solid/components/drawer'
    | '/_docs/solid/components/field'
    | '/_docs/solid/components/fieldset'
    | '/_docs/solid/components/form'
    | '/_docs/solid/components/input'
    | '/_docs/solid/components/menu'
    | '/_docs/solid/components/menubar'
    | '/_docs/solid/components/meter'
    | '/_docs/solid/components/navigation-menu'
    | '/_docs/solid/components/number-field'
    | '/_docs/solid/components/otp-field'
    | '/_docs/solid/components/popover'
    | '/_docs/solid/components/preview-card'
    | '/_docs/solid/components/progress'
    | '/_docs/solid/components/radio-group'
    | '/_docs/solid/components/scroll-area'
    | '/_docs/solid/components/select'
    | '/_docs/solid/components/separator'
    | '/_docs/solid/components/slider'
    | '/_docs/solid/components/switch'
    | '/_docs/solid/components/tabs'
    | '/_docs/solid/components/toast'
    | '/_docs/solid/components/toggle'
    | '/_docs/solid/components/toggle-group'
    | '/_docs/solid/components/toolbar'
    | '/_docs/solid/components/tooltip'
    | '/_docs/solid/handbook/animation'
    | '/_docs/solid/handbook/composition'
    | '/_docs/solid/handbook/customization'
    | '/_docs/solid/handbook/forms'
    | '/_docs/solid/handbook/styling'
    | '/_docs/solid/handbook/typescript'
    | '/_docs/solid/overview/about'
    | '/_docs/solid/overview/accessibility'
    | '/_docs/solid/overview/community'
    | '/_docs/solid/overview/quick-start'
    | '/_docs/solid/overview/releases'
    | '/_docs/solid/utils/csp-provider'
    | '/_docs/solid/utils/direction-provider'
    | '/_docs/solid/utils/merge-props'
    | '/_docs/solid/utils/use-render'
    | '/_docs/solid/components/'
    | '/_docs/solid/handbook/'
    | '/_docs/solid/overview/'
    | '/_docs/solid/utils/'
    | '/_docs/solid/overview/releases/v0-0-1'
    | '/_docs/solid/overview/releases/v0-1-0'
    | '/_docs/solid/overview/releases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DocsRoute: typeof DocsRouteWithChildren
  PrivateRoute: typeof PrivateRouteWithChildren
  WebsiteRoute: typeof WebsiteRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_docs': {
      id: '/_docs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_website': {
      id: '/_website'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs/production-error': {
      id: '/_docs/production-error'
      path: '/production-error'
      fullPath: '/production-error'
      preLoaderRoute: typeof DocsProductionErrorRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/solid': {
      id: '/_docs/solid'
      path: '/solid'
      fullPath: '/solid'
      preLoaderRoute: typeof DocsSolidRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_private/playground': {
      id: '/_private/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PrivatePlaygroundRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_website/': {
      id: '/_website/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WebsiteIndexRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/_docs/solid/': {
      id: '/_docs/solid/'
      path: '/'
      fullPath: '/solid/'
      preLoaderRoute: typeof DocsSolidIndexRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/handbook': {
      id: '/_docs/solid/handbook'
      path: '/handbook'
      fullPath: '/solid/handbook'
      preLoaderRoute: typeof DocsSolidHandbookRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/overview': {
      id: '/_docs/solid/overview'
      path: '/overview'
      fullPath: '/solid/overview'
      preLoaderRoute: typeof DocsSolidOverviewRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/utils': {
      id: '/_docs/solid/utils'
      path: '/utils'
      fullPath: '/solid/utils'
      preLoaderRoute: typeof DocsSolidUtilsRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/': {
      id: '/_docs/solid/components/'
      path: '/components'
      fullPath: '/solid/components/'
      preLoaderRoute: typeof DocsSolidComponentsIndexRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/accordion': {
      id: '/_docs/solid/components/accordion'
      path: '/components/accordion'
      fullPath: '/solid/components/accordion'
      preLoaderRoute: typeof DocsSolidComponentsAccordionRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/alert-dialog': {
      id: '/_docs/solid/components/alert-dialog'
      path: '/components/alert-dialog'
      fullPath: '/solid/components/alert-dialog'
      preLoaderRoute: typeof DocsSolidComponentsAlertDialogRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/autocomplete': {
      id: '/_docs/solid/components/autocomplete'
      path: '/components/autocomplete'
      fullPath: '/solid/components/autocomplete'
      preLoaderRoute: typeof DocsSolidComponentsAutocompleteRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/avatar': {
      id: '/_docs/solid/components/avatar'
      path: '/components/avatar'
      fullPath: '/solid/components/avatar'
      preLoaderRoute: typeof DocsSolidComponentsAvatarRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/button': {
      id: '/_docs/solid/components/button'
      path: '/components/button'
      fullPath: '/solid/components/button'
      preLoaderRoute: typeof DocsSolidComponentsButtonRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/checkbox': {
      id: '/_docs/solid/components/checkbox'
      path: '/components/checkbox'
      fullPath: '/solid/components/checkbox'
      preLoaderRoute: typeof DocsSolidComponentsCheckboxRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/checkbox-group': {
      id: '/_docs/solid/components/checkbox-group'
      path: '/components/checkbox-group'
      fullPath: '/solid/components/checkbox-group'
      preLoaderRoute: typeof DocsSolidComponentsCheckboxGroupRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/collapsible': {
      id: '/_docs/solid/components/collapsible'
      path: '/components/collapsible'
      fullPath: '/solid/components/collapsible'
      preLoaderRoute: typeof DocsSolidComponentsCollapsibleRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/combobox': {
      id: '/_docs/solid/components/combobox'
      path: '/components/combobox'
      fullPath: '/solid/components/combobox'
      preLoaderRoute: typeof DocsSolidComponentsComboboxRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/context-menu': {
      id: '/_docs/solid/components/context-menu'
      path: '/components/context-menu'
      fullPath: '/solid/components/context-menu'
      preLoaderRoute: typeof DocsSolidComponentsContextMenuRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/dialog': {
      id: '/_docs/solid/components/dialog'
      path: '/components/dialog'
      fullPath: '/solid/components/dialog'
      preLoaderRoute: typeof DocsSolidComponentsDialogRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/drawer': {
      id: '/_docs/solid/components/drawer'
      path: '/components/drawer'
      fullPath: '/solid/components/drawer'
      preLoaderRoute: typeof DocsSolidComponentsDrawerRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/field': {
      id: '/_docs/solid/components/field'
      path: '/components/field'
      fullPath: '/solid/components/field'
      preLoaderRoute: typeof DocsSolidComponentsFieldRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/fieldset': {
      id: '/_docs/solid/components/fieldset'
      path: '/components/fieldset'
      fullPath: '/solid/components/fieldset'
      preLoaderRoute: typeof DocsSolidComponentsFieldsetRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/form': {
      id: '/_docs/solid/components/form'
      path: '/components/form'
      fullPath: '/solid/components/form'
      preLoaderRoute: typeof DocsSolidComponentsFormRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/input': {
      id: '/_docs/solid/components/input'
      path: '/components/input'
      fullPath: '/solid/components/input'
      preLoaderRoute: typeof DocsSolidComponentsInputRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/menu': {
      id: '/_docs/solid/components/menu'
      path: '/components/menu'
      fullPath: '/solid/components/menu'
      preLoaderRoute: typeof DocsSolidComponentsMenuRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/menubar': {
      id: '/_docs/solid/components/menubar'
      path: '/components/menubar'
      fullPath: '/solid/components/menubar'
      preLoaderRoute: typeof DocsSolidComponentsMenubarRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/meter': {
      id: '/_docs/solid/components/meter'
      path: '/components/meter'
      fullPath: '/solid/components/meter'
      preLoaderRoute: typeof DocsSolidComponentsMeterRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/navigation-menu': {
      id: '/_docs/solid/components/navigation-menu'
      path: '/components/navigation-menu'
      fullPath: '/solid/components/navigation-menu'
      preLoaderRoute: typeof DocsSolidComponentsNavigationMenuRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/number-field': {
      id: '/_docs/solid/components/number-field'
      path: '/components/number-field'
      fullPath: '/solid/components/number-field'
      preLoaderRoute: typeof DocsSolidComponentsNumberFieldRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/otp-field': {
      id: '/_docs/solid/components/otp-field'
      path: '/components/otp-field'
      fullPath: '/solid/components/otp-field'
      preLoaderRoute: typeof DocsSolidComponentsOtpFieldRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/popover': {
      id: '/_docs/solid/components/popover'
      path: '/components/popover'
      fullPath: '/solid/components/popover'
      preLoaderRoute: typeof DocsSolidComponentsPopoverRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/preview-card': {
      id: '/_docs/solid/components/preview-card'
      path: '/components/preview-card'
      fullPath: '/solid/components/preview-card'
      preLoaderRoute: typeof DocsSolidComponentsPreviewCardRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/progress': {
      id: '/_docs/solid/components/progress'
      path: '/components/progress'
      fullPath: '/solid/components/progress'
      preLoaderRoute: typeof DocsSolidComponentsProgressRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/radio-group': {
      id: '/_docs/solid/components/radio-group'
      path: '/components/radio-group'
      fullPath: '/solid/components/radio-group'
      preLoaderRoute: typeof DocsSolidComponentsRadioGroupRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/scroll-area': {
      id: '/_docs/solid/components/scroll-area'
      path: '/components/scroll-area'
      fullPath: '/solid/components/scroll-area'
      preLoaderRoute: typeof DocsSolidComponentsScrollAreaRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/select': {
      id: '/_docs/solid/components/select'
      path: '/components/select'
      fullPath: '/solid/components/select'
      preLoaderRoute: typeof DocsSolidComponentsSelectRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/separator': {
      id: '/_docs/solid/components/separator'
      path: '/components/separator'
      fullPath: '/solid/components/separator'
      preLoaderRoute: typeof DocsSolidComponentsSeparatorRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/slider': {
      id: '/_docs/solid/components/slider'
      path: '/components/slider'
      fullPath: '/solid/components/slider'
      preLoaderRoute: typeof DocsSolidComponentsSliderRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/switch': {
      id: '/_docs/solid/components/switch'
      path: '/components/switch'
      fullPath: '/solid/components/switch'
      preLoaderRoute: typeof DocsSolidComponentsSwitchRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/tabs': {
      id: '/_docs/solid/components/tabs'
      path: '/components/tabs'
      fullPath: '/solid/components/tabs'
      preLoaderRoute: typeof DocsSolidComponentsTabsRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/toast': {
      id: '/_docs/solid/components/toast'
      path: '/components/toast'
      fullPath: '/solid/components/toast'
      preLoaderRoute: typeof DocsSolidComponentsToastRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/toggle': {
      id: '/_docs/solid/components/toggle'
      path: '/components/toggle'
      fullPath: '/solid/components/toggle'
      preLoaderRoute: typeof DocsSolidComponentsToggleRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/toggle-group': {
      id: '/_docs/solid/components/toggle-group'
      path: '/components/toggle-group'
      fullPath: '/solid/components/toggle-group'
      preLoaderRoute: typeof DocsSolidComponentsToggleGroupRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/toolbar': {
      id: '/_docs/solid/components/toolbar'
      path: '/components/toolbar'
      fullPath: '/solid/components/toolbar'
      preLoaderRoute: typeof DocsSolidComponentsToolbarRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/components/tooltip': {
      id: '/_docs/solid/components/tooltip'
      path: '/components/tooltip'
      fullPath: '/solid/components/tooltip'
      preLoaderRoute: typeof DocsSolidComponentsTooltipRouteImport
      parentRoute: typeof DocsSolidRoute
    }
    '/_docs/solid/handbook/': {
      id: '/_docs/solid/handbook/'
      path: '/'
      fullPath: '/solid/handbook/'
      preLoaderRoute: typeof DocsSolidHandbookIndexRouteImport
      parentRoute: typeof DocsSolidHandbookRoute
    }
    '/_docs/solid/handbook/animation': {
      id: '/_docs/solid/handbook/animation'
      path: '/animation'
      fullPath: '/solid/handbook/animation'
      preLoaderRoute: typeof DocsSolidHandbookAnimationRouteImport
      parentRoute: typeof DocsSolidHandbookRoute
    }
    '/_docs/solid/handbook/composition': {
      id: '/_docs/solid/handbook/composition'
      path: '/composition'
      fullPath: '/solid/handbook/composition'
      preLoaderRoute: typeof DocsSolidHandbookCompositionRouteImport
      parentRoute: typeof DocsSolidHandbookRoute
    }
    '/_docs/solid/handbook/customization': {
      id: '/_docs/solid/handbook/customization'
      path: '/customization'
      fullPath: '/solid/handbook/customization'
      preLoaderRoute: typeof DocsSolidHandbookCustomizationRouteImport
      parentRoute: typeof DocsSolidHandbookRoute
    }
    '/_docs/solid/handbook/forms': {
      id: '/_docs/solid/handbook/forms'
      path: '/forms'
      fullPath: '/solid/handbook/forms'
      preLoaderRoute: typeof DocsSolidHandbookFormsRouteImport
      parentRoute: typeof DocsSolidHandbookRoute
    }
    '/_docs/solid/handbook/styling': {
      id: '/_docs/solid/handbook/styling'
      path: '/styling'
      fullPath: '/solid/handbook/styling'
      preLoaderRoute: typeof DocsSolidHandbookStylingRouteImport
      parentRoute: typeof DocsSolidHandbookRoute
    }
    '/_docs/solid/handbook/typescript': {
      id: '/_docs/solid/handbook/typescript'
      path: '/typescript'
      fullPath: '/solid/handbook/typescript'
      preLoaderRoute: typeof DocsSolidHandbookTypescriptRouteImport
      parentRoute: typeof DocsSolidHandbookRoute
    }
    '/_docs/solid/overview/': {
      id: '/_docs/solid/overview/'
      path: '/'
      fullPath: '/solid/overview/'
      preLoaderRoute: typeof DocsSolidOverviewIndexRouteImport
      parentRoute: typeof DocsSolidOverviewRoute
    }
    '/_docs/solid/overview/about': {
      id: '/_docs/solid/overview/about'
      path: '/about'
      fullPath: '/solid/overview/about'
      preLoaderRoute: typeof DocsSolidOverviewAboutRouteImport
      parentRoute: typeof DocsSolidOverviewRoute
    }
    '/_docs/solid/overview/accessibility': {
      id: '/_docs/solid/overview/accessibility'
      path: '/accessibility'
      fullPath: '/solid/overview/accessibility'
      preLoaderRoute: typeof DocsSolidOverviewAccessibilityRouteImport
      parentRoute: typeof DocsSolidOverviewRoute
    }
    '/_docs/solid/overview/community': {
      id: '/_docs/solid/overview/community'
      path: '/community'
      fullPath: '/solid/overview/community'
      preLoaderRoute: typeof DocsSolidOverviewCommunityRouteImport
      parentRoute: typeof DocsSolidOverviewRoute
    }
    '/_docs/solid/overview/quick-start': {
      id: '/_docs/solid/overview/quick-start'
      path: '/quick-start'
      fullPath: '/solid/overview/quick-start'
      preLoaderRoute: typeof DocsSolidOverviewQuickStartRouteImport
      parentRoute: typeof DocsSolidOverviewRoute
    }
    '/_docs/solid/overview/releases': {
      id: '/_docs/solid/overview/releases'
      path: '/releases'
      fullPath: '/solid/overview/releases'
      preLoaderRoute: typeof DocsSolidOverviewReleasesRouteImport
      parentRoute: typeof DocsSolidOverviewRoute
    }
    '/_docs/solid/utils/': {
      id: '/_docs/solid/utils/'
      path: '/'
      fullPath: '/solid/utils/'
      preLoaderRoute: typeof DocsSolidUtilsIndexRouteImport
      parentRoute: typeof DocsSolidUtilsRoute
    }
    '/_docs/solid/utils/csp-provider': {
      id: '/_docs/solid/utils/csp-provider'
      path: '/csp-provider'
      fullPath: '/solid/utils/csp-provider'
      preLoaderRoute: typeof DocsSolidUtilsCspProviderRouteImport
      parentRoute: typeof DocsSolidUtilsRoute
    }
    '/_docs/solid/utils/direction-provider': {
      id: '/_docs/solid/utils/direction-provider'
      path: '/direction-provider'
      fullPath: '/solid/utils/direction-provider'
      preLoaderRoute: typeof DocsSolidUtilsDirectionProviderRouteImport
      parentRoute: typeof DocsSolidUtilsRoute
    }
    '/_docs/solid/utils/merge-props': {
      id: '/_docs/solid/utils/merge-props'
      path: '/merge-props'
      fullPath: '/solid/utils/merge-props'
      preLoaderRoute: typeof DocsSolidUtilsMergePropsRouteImport
      parentRoute: typeof DocsSolidUtilsRoute
    }
    '/_docs/solid/utils/use-render': {
      id: '/_docs/solid/utils/use-render'
      path: '/use-render'
      fullPath: '/solid/utils/use-render'
      preLoaderRoute: typeof DocsSolidUtilsUseRenderRouteImport
      parentRoute: typeof DocsSolidUtilsRoute
    }
    '/_docs/solid/overview/releases/': {
      id: '/_docs/solid/overview/releases/'
      path: '/'
      fullPath: '/solid/overview/releases/'
      preLoaderRoute: typeof DocsSolidOverviewReleasesIndexRouteImport
      parentRoute: typeof DocsSolidOverviewReleasesRoute
    }
    '/_docs/solid/overview/releases/v0-0-1': {
      id: '/_docs/solid/overview/releases/v0-0-1'
      path: '/v0-0-1'
      fullPath: '/solid/overview/releases/v0-0-1'
      preLoaderRoute: typeof DocsSolidOverviewReleasesV001RouteImport
      parentRoute: typeof DocsSolidOverviewReleasesRoute
    }
    '/_docs/solid/overview/releases/v0-1-0': {
      id: '/_docs/solid/overview/releases/v0-1-0'
      path: '/v0-1-0'
      fullPath: '/solid/overview/releases/v0-1-0'
      preLoaderRoute: typeof DocsSolidOverviewReleasesV010RouteImport
      parentRoute: typeof DocsSolidOverviewReleasesRoute
    }
  }
}

interface DocsSolidHandbookRouteChildren {
  DocsSolidHandbookAnimationRoute: typeof DocsSolidHandbookAnimationRoute
  DocsSolidHandbookCompositionRoute: typeof DocsSolidHandbookCompositionRoute
  DocsSolidHandbookCustomizationRoute: typeof DocsSolidHandbookCustomizationRoute
  DocsSolidHandbookFormsRoute: typeof DocsSolidHandbookFormsRoute
  DocsSolidHandbookStylingRoute: typeof DocsSolidHandbookStylingRoute
  DocsSolidHandbookTypescriptRoute: typeof DocsSolidHandbookTypescriptRoute
  DocsSolidHandbookIndexRoute: typeof DocsSolidHandbookIndexRoute
}

const DocsSolidHandbookRouteChildren: DocsSolidHandbookRouteChildren = {
  DocsSolidHandbookAnimationRoute: DocsSolidHandbookAnimationRoute,
  DocsSolidHandbookCompositionRoute: DocsSolidHandbookCompositionRoute,
  DocsSolidHandbookCustomizationRoute: DocsSolidHandbookCustomizationRoute,
  DocsSolidHandbookFormsRoute: DocsSolidHandbookFormsRoute,
  DocsSolidHandbookStylingRoute: DocsSolidHandbookStylingRoute,
  DocsSolidHandbookTypescriptRoute: DocsSolidHandbookTypescriptRoute,
  DocsSolidHandbookIndexRoute: DocsSolidHandbookIndexRoute,
}

const DocsSolidHandbookRouteWithChildren =
  DocsSolidHandbookRoute._addFileChildren(DocsSolidHandbookRouteChildren)

interface DocsSolidOverviewReleasesRouteChildren {
  DocsSolidOverviewReleasesV001Route: typeof DocsSolidOverviewReleasesV001Route
  DocsSolidOverviewReleasesV010Route: typeof DocsSolidOverviewReleasesV010Route
  DocsSolidOverviewReleasesIndexRoute: typeof DocsSolidOverviewReleasesIndexRoute
}

const DocsSolidOverviewReleasesRouteChildren: DocsSolidOverviewReleasesRouteChildren =
  {
    DocsSolidOverviewReleasesV001Route: DocsSolidOverviewReleasesV001Route,
    DocsSolidOverviewReleasesV010Route: DocsSolidOverviewReleasesV010Route,
    DocsSolidOverviewReleasesIndexRoute: DocsSolidOverviewReleasesIndexRoute,
  }

const DocsSolidOverviewReleasesRouteWithChildren =
  DocsSolidOverviewReleasesRoute._addFileChildren(
    DocsSolidOverviewReleasesRouteChildren,
  )

interface DocsSolidOverviewRouteChildren {
  DocsSolidOverviewAboutRoute: typeof DocsSolidOverviewAboutRoute
  DocsSolidOverviewAccessibilityRoute: typeof DocsSolidOverviewAccessibilityRoute
  DocsSolidOverviewCommunityRoute: typeof DocsSolidOverviewCommunityRoute
  DocsSolidOverviewQuickStartRoute: typeof DocsSolidOverviewQuickStartRoute
  DocsSolidOverviewReleasesRoute: typeof DocsSolidOverviewReleasesRouteWithChildren
  DocsSolidOverviewIndexRoute: typeof DocsSolidOverviewIndexRoute
}

const DocsSolidOverviewRouteChildren: DocsSolidOverviewRouteChildren = {
  DocsSolidOverviewAboutRoute: DocsSolidOverviewAboutRoute,
  DocsSolidOverviewAccessibilityRoute: DocsSolidOverviewAccessibilityRoute,
  DocsSolidOverviewCommunityRoute: DocsSolidOverviewCommunityRoute,
  DocsSolidOverviewQuickStartRoute: DocsSolidOverviewQuickStartRoute,
  DocsSolidOverviewReleasesRoute: DocsSolidOverviewReleasesRouteWithChildren,
  DocsSolidOverviewIndexRoute: DocsSolidOverviewIndexRoute,
}

const DocsSolidOverviewRouteWithChildren =
  DocsSolidOverviewRoute._addFileChildren(DocsSolidOverviewRouteChildren)

interface DocsSolidUtilsRouteChildren {
  DocsSolidUtilsCspProviderRoute: typeof DocsSolidUtilsCspProviderRoute
  DocsSolidUtilsDirectionProviderRoute: typeof DocsSolidUtilsDirectionProviderRoute
  DocsSolidUtilsMergePropsRoute: typeof DocsSolidUtilsMergePropsRoute
  DocsSolidUtilsUseRenderRoute: typeof DocsSolidUtilsUseRenderRoute
  DocsSolidUtilsIndexRoute: typeof DocsSolidUtilsIndexRoute
}

const DocsSolidUtilsRouteChildren: DocsSolidUtilsRouteChildren = {
  DocsSolidUtilsCspProviderRoute: DocsSolidUtilsCspProviderRoute,
  DocsSolidUtilsDirectionProviderRoute: DocsSolidUtilsDirectionProviderRoute,
  DocsSolidUtilsMergePropsRoute: DocsSolidUtilsMergePropsRoute,
  DocsSolidUtilsUseRenderRoute: DocsSolidUtilsUseRenderRoute,
  DocsSolidUtilsIndexRoute: DocsSolidUtilsIndexRoute,
}

const DocsSolidUtilsRouteWithChildren = DocsSolidUtilsRoute._addFileChildren(
  DocsSolidUtilsRouteChildren,
)

interface DocsSolidRouteChildren {
  DocsSolidHandbookRoute: typeof DocsSolidHandbookRouteWithChildren
  DocsSolidOverviewRoute: typeof DocsSolidOverviewRouteWithChildren
  DocsSolidUtilsRoute: typeof DocsSolidUtilsRouteWithChildren
  DocsSolidIndexRoute: typeof DocsSolidIndexRoute
  DocsSolidComponentsAccordionRoute: typeof DocsSolidComponentsAccordionRoute
  DocsSolidComponentsAlertDialogRoute: typeof DocsSolidComponentsAlertDialogRoute
  DocsSolidComponentsAutocompleteRoute: typeof DocsSolidComponentsAutocompleteRoute
  DocsSolidComponentsAvatarRoute: typeof DocsSolidComponentsAvatarRoute
  DocsSolidComponentsButtonRoute: typeof DocsSolidComponentsButtonRoute
  DocsSolidComponentsCheckboxRoute: typeof DocsSolidComponentsCheckboxRoute
  DocsSolidComponentsCheckboxGroupRoute: typeof DocsSolidComponentsCheckboxGroupRoute
  DocsSolidComponentsCollapsibleRoute: typeof DocsSolidComponentsCollapsibleRoute
  DocsSolidComponentsComboboxRoute: typeof DocsSolidComponentsComboboxRoute
  DocsSolidComponentsContextMenuRoute: typeof DocsSolidComponentsContextMenuRoute
  DocsSolidComponentsDialogRoute: typeof DocsSolidComponentsDialogRoute
  DocsSolidComponentsDrawerRoute: typeof DocsSolidComponentsDrawerRoute
  DocsSolidComponentsFieldRoute: typeof DocsSolidComponentsFieldRoute
  DocsSolidComponentsFieldsetRoute: typeof DocsSolidComponentsFieldsetRoute
  DocsSolidComponentsFormRoute: typeof DocsSolidComponentsFormRoute
  DocsSolidComponentsInputRoute: typeof DocsSolidComponentsInputRoute
  DocsSolidComponentsMenuRoute: typeof DocsSolidComponentsMenuRoute
  DocsSolidComponentsMenubarRoute: typeof DocsSolidComponentsMenubarRoute
  DocsSolidComponentsMeterRoute: typeof DocsSolidComponentsMeterRoute
  DocsSolidComponentsNavigationMenuRoute: typeof DocsSolidComponentsNavigationMenuRoute
  DocsSolidComponentsNumberFieldRoute: typeof DocsSolidComponentsNumberFieldRoute
  DocsSolidComponentsOtpFieldRoute: typeof DocsSolidComponentsOtpFieldRoute
  DocsSolidComponentsPopoverRoute: typeof DocsSolidComponentsPopoverRoute
  DocsSolidComponentsPreviewCardRoute: typeof DocsSolidComponentsPreviewCardRoute
  DocsSolidComponentsProgressRoute: typeof DocsSolidComponentsProgressRoute
  DocsSolidComponentsRadioGroupRoute: typeof DocsSolidComponentsRadioGroupRoute
  DocsSolidComponentsScrollAreaRoute: typeof DocsSolidComponentsScrollAreaRoute
  DocsSolidComponentsSelectRoute: typeof DocsSolidComponentsSelectRoute
  DocsSolidComponentsSeparatorRoute: typeof DocsSolidComponentsSeparatorRoute
  DocsSolidComponentsSliderRoute: typeof DocsSolidComponentsSliderRoute
  DocsSolidComponentsSwitchRoute: typeof DocsSolidComponentsSwitchRoute
  DocsSolidComponentsTabsRoute: typeof DocsSolidComponentsTabsRoute
  DocsSolidComponentsToastRoute: typeof DocsSolidComponentsToastRoute
  DocsSolidComponentsToggleRoute: typeof DocsSolidComponentsToggleRoute
  DocsSolidComponentsToggleGroupRoute: typeof DocsSolidComponentsToggleGroupRoute
  DocsSolidComponentsToolbarRoute: typeof DocsSolidComponentsToolbarRoute
  DocsSolidComponentsTooltipRoute: typeof DocsSolidComponentsTooltipRoute
  DocsSolidComponentsIndexRoute: typeof DocsSolidComponentsIndexRoute
}

const DocsSolidRouteChildren: DocsSolidRouteChildren = {
  DocsSolidHandbookRoute: DocsSolidHandbookRouteWithChildren,
  DocsSolidOverviewRoute: DocsSolidOverviewRouteWithChildren,
  DocsSolidUtilsRoute: DocsSolidUtilsRouteWithChildren,
  DocsSolidIndexRoute: DocsSolidIndexRoute,
  DocsSolidComponentsAccordionRoute: DocsSolidComponentsAccordionRoute,
  DocsSolidComponentsAlertDialogRoute: DocsSolidComponentsAlertDialogRoute,
  DocsSolidComponentsAutocompleteRoute: DocsSolidComponentsAutocompleteRoute,
  DocsSolidComponentsAvatarRoute: DocsSolidComponentsAvatarRoute,
  DocsSolidComponentsButtonRoute: DocsSolidComponentsButtonRoute,
  DocsSolidComponentsCheckboxRoute: DocsSolidComponentsCheckboxRoute,
  DocsSolidComponentsCheckboxGroupRoute: DocsSolidComponentsCheckboxGroupRoute,
  DocsSolidComponentsCollapsibleRoute: DocsSolidComponentsCollapsibleRoute,
  DocsSolidComponentsComboboxRoute: DocsSolidComponentsComboboxRoute,
  DocsSolidComponentsContextMenuRoute: DocsSolidComponentsContextMenuRoute,
  DocsSolidComponentsDialogRoute: DocsSolidComponentsDialogRoute,
  DocsSolidComponentsDrawerRoute: DocsSolidComponentsDrawerRoute,
  DocsSolidComponentsFieldRoute: DocsSolidComponentsFieldRoute,
  DocsSolidComponentsFieldsetRoute: DocsSolidComponentsFieldsetRoute,
  DocsSolidComponentsFormRoute: DocsSolidComponentsFormRoute,
  DocsSolidComponentsInputRoute: DocsSolidComponentsInputRoute,
  DocsSolidComponentsMenuRoute: DocsSolidComponentsMenuRoute,
  DocsSolidComponentsMenubarRoute: DocsSolidComponentsMenubarRoute,
  DocsSolidComponentsMeterRoute: DocsSolidComponentsMeterRoute,
  DocsSolidComponentsNavigationMenuRoute:
    DocsSolidComponentsNavigationMenuRoute,
  DocsSolidComponentsNumberFieldRoute: DocsSolidComponentsNumberFieldRoute,
  DocsSolidComponentsOtpFieldRoute: DocsSolidComponentsOtpFieldRoute,
  DocsSolidComponentsPopoverRoute: DocsSolidComponentsPopoverRoute,
  DocsSolidComponentsPreviewCardRoute: DocsSolidComponentsPreviewCardRoute,
  DocsSolidComponentsProgressRoute: DocsSolidComponentsProgressRoute,
  DocsSolidComponentsRadioGroupRoute: DocsSolidComponentsRadioGroupRoute,
  DocsSolidComponentsScrollAreaRoute: DocsSolidComponentsScrollAreaRoute,
  DocsSolidComponentsSelectRoute: DocsSolidComponentsSelectRoute,
  DocsSolidComponentsSeparatorRoute: DocsSolidComponentsSeparatorRoute,
  DocsSolidComponentsSliderRoute: DocsSolidComponentsSliderRoute,
  DocsSolidComponentsSwitchRoute: DocsSolidComponentsSwitchRoute,
  DocsSolidComponentsTabsRoute: DocsSolidComponentsTabsRoute,
  DocsSolidComponentsToastRoute: DocsSolidComponentsToastRoute,
  DocsSolidComponentsToggleRoute: DocsSolidComponentsToggleRoute,
  DocsSolidComponentsToggleGroupRoute: DocsSolidComponentsToggleGroupRoute,
  DocsSolidComponentsToolbarRoute: DocsSolidComponentsToolbarRoute,
  DocsSolidComponentsTooltipRoute: DocsSolidComponentsTooltipRoute,
  DocsSolidComponentsIndexRoute: DocsSolidComponentsIndexRoute,
}

const DocsSolidRouteWithChildren = DocsSolidRoute._addFileChildren(
  DocsSolidRouteChildren,
)

interface DocsRouteChildren {
  DocsProductionErrorRoute: typeof DocsProductionErrorRoute
  DocsSolidRoute: typeof DocsSolidRouteWithChildren
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsProductionErrorRoute: DocsProductionErrorRoute,
  DocsSolidRoute: DocsSolidRouteWithChildren,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface PrivateRouteChildren {
  PrivatePlaygroundRoute: typeof PrivatePlaygroundRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivatePlaygroundRoute: PrivatePlaygroundRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface WebsiteRouteChildren {
  WebsiteIndexRoute: typeof WebsiteIndexRoute
}

const WebsiteRouteChildren: WebsiteRouteChildren = {
  WebsiteIndexRoute: WebsiteIndexRoute,
}

const WebsiteRouteWithChildren =
  WebsiteRoute._addFileChildren(WebsiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DocsRoute: DocsRouteWithChildren,
  PrivateRoute: PrivateRouteWithChildren,
  WebsiteRoute: WebsiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
