/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/_docs'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as WebsiteRouteImport } from './routes/_website'
import { Route as PrivatePlaygroundRouteImport } from './routes/_private.playground'
import { Route as WebsiteIndexRouteImport } from './routes/_website.index'
import { Route as DocsReactComponentsCollapsibleRouteImport } from './routes/_docs.react.components.collapsible'

const DocsRoute = DocsRouteImport.update({
  id: '/_docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteRoute = WebsiteRouteImport.update({
  id: '/_website',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatePlaygroundRoute = PrivatePlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => PrivateRoute,
} as any)
const WebsiteIndexRoute = WebsiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebsiteRoute,
} as any)
const DocsReactComponentsCollapsibleRoute =
  DocsReactComponentsCollapsibleRouteImport.update({
    id: '/react/components/collapsible',
    path: '/react/components/collapsible',
    getParentRoute: () => DocsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WebsiteIndexRoute
  '/playground': typeof PrivatePlaygroundRoute
  '/react/components/collapsible': typeof DocsReactComponentsCollapsibleRoute
}
export interface FileRoutesByTo {
  '/': typeof WebsiteIndexRoute
  '/playground': typeof PrivatePlaygroundRoute
  '/react/components/collapsible': typeof DocsReactComponentsCollapsibleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_docs': typeof DocsRouteWithChildren
  '/_private': typeof PrivateRouteWithChildren
  '/_website': typeof WebsiteRouteWithChildren
  '/_private/playground': typeof PrivatePlaygroundRoute
  '/_website/': typeof WebsiteIndexRoute
  '/_docs/react/components/collapsible': typeof DocsReactComponentsCollapsibleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/playground' | '/react/components/collapsible'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/playground' | '/react/components/collapsible'
  id:
    | '__root__'
    | '/_docs'
    | '/_private'
    | '/_website'
    | '/_private/playground'
    | '/_website/'
    | '/_docs/react/components/collapsible'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DocsRoute: typeof DocsRouteWithChildren
  PrivateRoute: typeof PrivateRouteWithChildren
  WebsiteRoute: typeof WebsiteRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_docs': {
      id: '/_docs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_website': {
      id: '/_website'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/playground': {
      id: '/_private/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PrivatePlaygroundRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_website/': {
      id: '/_website/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WebsiteIndexRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/_docs/react/components/collapsible': {
      id: '/_docs/react/components/collapsible'
      path: '/react/components/collapsible'
      fullPath: '/react/components/collapsible'
      preLoaderRoute: typeof DocsReactComponentsCollapsibleRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsReactComponentsCollapsibleRoute: typeof DocsReactComponentsCollapsibleRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsReactComponentsCollapsibleRoute: DocsReactComponentsCollapsibleRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface PrivateRouteChildren {
  PrivatePlaygroundRoute: typeof PrivatePlaygroundRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivatePlaygroundRoute: PrivatePlaygroundRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface WebsiteRouteChildren {
  WebsiteIndexRoute: typeof WebsiteIndexRoute
}

const WebsiteRouteChildren: WebsiteRouteChildren = {
  WebsiteIndexRoute: WebsiteIndexRoute,
}

const WebsiteRouteWithChildren =
  WebsiteRoute._addFileChildren(WebsiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DocsRoute: DocsRouteWithChildren,
  PrivateRoute: PrivateRouteWithChildren,
  WebsiteRoute: WebsiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
